on:
  push:
    branches:
      - main
      - master
      - development
      - LandWeb
  pull_request:
    branches:
      - main
      - master
      - development

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}, nosuggests ${{ matrix.config.nosuggests }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,    nosuggests: false, r: 'release'}
          - {os: windows-latest,  nosuggests: false, r: 'devel'}
          - {os: windows-latest,  nosuggests: false, r: 'release'}
          - {os: windows-latest,  nosuggests: false, r: 'oldrel-1'}
          - {os: windows-latest,  nosuggests: false, r: 'oldrel-2'}
          - {os: ubuntu-latest,   nosuggests: false, r: 'devel'}
          - {os: ubuntu-latest,   nosuggests: false, r: 'release'}
          - {os: ubuntu-latest,   nosuggests: true,  r: 'release'}
          - {os: ubuntu-latest,   nosuggests: false, r: 'oldrel-1'}
          - {os: ubuntu-latest,   nosuggests: false, r: 'oldrel-2'}

    env:
      _R_CHECK_DEPENDS_ONLY_: ${{ matrix.config.nosuggests }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: PredictiveEcology/actions/install-spatial-deps@v0.2

      - uses: r-lib/actions/setup-r@v2
        with:
          Ncpus: 2
          r-version: ${{ matrix.config.r }}
          use-public-rspm: false

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
